name = "tvbox-source-hub-v73"
main = "src/worker.mjs"
compatibility_date = "2024-11-01"
workers_dev = true
preview_urls = true

routes = [
  { pattern = "tv.webhome.eu.org", custom_domain = true },
  { pattern = "tv.webclound.eu.org", custom_domain = true }
]

[[kv_namespaces]]
binding = "TVBOX_KV"
id = "398f07fafd0b463da486b623a00b57ba"

[vars]
SNAPSHOT_BASES = "https://raw.githubusercontent.com/webmoneyfeng/tvbox-source-hub-v73/main/dist/snapshot/latest|https://tvbox-source-hub-v73.pages.dev/snapshot/latest|https://tv.webhome.eu.org/static/snapshot/latest|https://tv.webclound.eu.org/static/snapshot/latest"

[triggers]
crons = ["*/2 * * * *"]
